# rse_fsd/config/dashcam_params1.yaml

# Parameters for the node named 'dashcam_node'
dashcam_node:
  # The special key 'ros__parameters' indicates the following are ROS parameters
  ros__parameters:
    display_resolution: 1080    # Set resolution to 720p
    show_detections: true     # Turn ON detection display
    bbox_color: "blue"       # Set bounding box color to green (quotes optional but good practice for strings)

